/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const ShowcaseIndexLazyImport = createFileRoute("/showcase/")();
const ShowcaseAboutLazyImport = createFileRoute("/showcase/about")();

// Create/Update Routes

const ShowcaseIndexLazyRoute = ShowcaseIndexLazyImport.update({
  id: "/showcase/",
  path: "/showcase/",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/showcase.index.lazy").then((d) => d.Route),
);

const ShowcaseAboutLazyRoute = ShowcaseAboutLazyImport.update({
  id: "/showcase/about",
  path: "/showcase/about",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/showcase.about.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/showcase/about": {
      id: "/showcase/about";
      path: "/showcase/about";
      fullPath: "/showcase/about";
      preLoaderRoute: typeof ShowcaseAboutLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/showcase/": {
      id: "/showcase/";
      path: "/showcase";
      fullPath: "/showcase";
      preLoaderRoute: typeof ShowcaseIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/showcase/about": typeof ShowcaseAboutLazyRoute;
  "/showcase": typeof ShowcaseIndexLazyRoute;
}

export interface FileRoutesByTo {
  "/showcase/about": typeof ShowcaseAboutLazyRoute;
  "/showcase": typeof ShowcaseIndexLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/showcase/about": typeof ShowcaseAboutLazyRoute;
  "/showcase/": typeof ShowcaseIndexLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/showcase/about" | "/showcase";
  fileRoutesByTo: FileRoutesByTo;
  to: "/showcase/about" | "/showcase";
  id: "__root__" | "/showcase/about" | "/showcase/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  ShowcaseAboutLazyRoute: typeof ShowcaseAboutLazyRoute;
  ShowcaseIndexLazyRoute: typeof ShowcaseIndexLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  ShowcaseAboutLazyRoute: ShowcaseAboutLazyRoute,
  ShowcaseIndexLazyRoute: ShowcaseIndexLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/showcase/about",
        "/showcase/"
      ]
    },
    "/showcase/about": {
      "filePath": "showcase.about.lazy.tsx"
    },
    "/showcase/": {
      "filePath": "showcase.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
